import React from "react";
import Head from "next/head";
import Footer from "../../common/Footer";
import Topbar from "../../common/Topbar";
import LayoutHeader from "../header/LayoutHeader";
function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Sarthak Mittal - Advocates & Solicitors</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://vktlawchambers.com/wp-content/uploads/2022/10/VKT-Logo-2-300x300.png"
        />
      </Head>
      <Topbar />
      <LayoutHeader />
      {children}
      <Footer />
    </>
  );
}

export default Layout;
