import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const font = Raleway({ weight: "100", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Law",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-[#f9f7f5] text-black`}
        suppressHydrationWarning
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
