import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { ContactBanner } from "@/components/ContactBanner";

const font = Raleway({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Law",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} lg:pt-[7rem] pt-[4rem] antialiased bg-[#f9f7f5] text-black`}
        suppressHydrationWarning
      >
        <Header />
        {children}
        {/* <ContactBanner /> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
