// import { useEffect, useState } from "react";
// import Head from "next/head";
// import Footer from "../common/Footer";
// import InfoSection from "../common/InfoSection";
// import Preloader from "../common/Preloader";
// import About1 from "../components/about/About1";
// import Banner1 from "../components/banner/Banner1";
// import Header from "../components/header/Header";
// import AttronySection from "../components/home/AttronySection";
// import CaseStudy from "../components/home/CaseStudy";
// import ContactSection from "../components/home/ContactSection";
// import IntroSection from "../components/home/IntroSection";
// import LatestBlog from "../components/home/LatestBlog";
// import Practice from "../components/practice/Practice";
// import Testimonial1 from "../components/testimonial/Testimonial1";

// export default function Home() {
//   const [loading, setLoading] = useState(false);
//   useEffect(() => {
//     setLoading(true);
//     setTimeout(() => {
//       setLoading(false);
//     }, 3000);
//   }, []);
//   return (
//     <>
//       {loading ? (
//         <Preloader style="home1preloader" />
//       ) : (
//         <>
//           <Head>
//             <title>VKT- Advocates & Solicitors</title>
//             <meta name="description" content="Generated by create next app" />
//             <link rel="icon" href="assets/images/icons/logo-icon.svg" />
//           </Head>
//           <Header
//             logoLeft={`<Link href="/"><a><img alt="image" src="assets/images/icons/header1-logo.svg" /></a></Link>`}
//             styles="header-area style-1"
//           />
//           <Banner1 />
//           <IntroSection />
//           <About1 />
//           <Practice />
//           <InfoSection />
//           <CaseStudy style="casestudy-section2 pt-120 pb-120" />
//           <AttronySection />
//           <ContactSection />
//           <Testimonial1 />
//           <LatestBlog />
//           <Footer />
//         </>
//       )}
//     </>
//   );
// }

import React, { useEffect, useState } from "react";
import Head from "next/head";
import Footer from "../common/Footer";
import Preloader from "../common/Preloader";
import Topbar from "../common/Topbar";
import About2 from "../components/about/About2";
import AttronySection from "../components/Attrony/AttronySection";
import Banner2 from "../components/banner/Banner2";
import AboutBlog from "../components/blog/AboutBlog";
import CaseStudy from "../components/caseStudy/CaseStudy";
import AboutContactArea from "../components/contact/AboutContactArea";
import Header2 from "../components/header/Header2";
import IntroSection2 from "../components/introSection/IntroSection2";
import Practice2 from "../components/practice/Practice2";
import PracticeTestimonial from "../components/testimonial/PracticeTestimonial";
import Counter2 from "../counter/Counter2";
import Attrony2 from "../components/Attrony/Attrony2";
import CaseStudy3 from "../components/caseStudy/CaseStudy3";
import About3 from "../components/about/About3";

function Home2() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, []);
  return (
    <>
      {loading ? (
        <Preloader style="home2preloader" />
      ) : (
        <>
          <Head>
            <title>Sarthak Mittal - Advocates & Solicitors</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/icons/.png" />
          </Head>
          <Topbar />
          <Header2 />
          <Banner2 />
          <IntroSection2 />
          <About3  />
          {/* <About2 /> */}
          {/* <Practice2 /> */}
          <Counter2 />
          <Attrony2 />
          <CaseStudy3 style="casestudy-section2 pt-120" />
          {/* <CaseStudy2 style="casestudy-section2 pt-120" /> */}
          <PracticeTestimonial />
          <AboutContactArea />
          <AboutBlog paddin="pt-120" />
          <Footer />
        </>
      )}
    </>
  );
}

export default Home2;
